"""This file was code generated by turms. If you want to change the contents of this file, you should make sure to add the MergeProcessor to your config will keep your changes when you re-run turms)."""

from kabinet.funcs import execute, aexecute
from pydantic import BaseModel, Field, ConfigDict
from typing import Tuple, Optional, Literal
from enum import Enum
from kabinet.rath import KabinetRath
from rath.scalars import ID


class GetDetailDefinitionQueryDefinitionFlavours(BaseModel):
    """A user of the bridge server. Maps to an authentikate user"""

    typename: Literal["Flavour"] = Field(
        alias="__typename", default="Flavour", exclude=True
    )
    id: ID
    model_config = ConfigDict(frozen=True)


class GetDetailDefinitionQueryDefinition(BaseModel):
    """No documentation"""

    typename: Literal["Definition"] = Field(
        alias="__typename", default="Definition", exclude=True
    )
    id: ID
    flavours: Tuple[GetDetailDefinitionQueryDefinitionFlavours, ...]
    model_config = ConfigDict(frozen=True)


class GetDetailDefinitionQuery(BaseModel):
    """No documentation found for this operation."""

    definition: GetDetailDefinitionQueryDefinition
    "Return all dask clusters"

    class Arguments(BaseModel):
        """Arguments for GetDetailDefinition"""

        definition: ID
        model_config = ConfigDict(populate_by_name=True)

    class Meta:
        """Meta class for GetDetailDefinition"""

        document = "query GetDetailDefinition($definition: ID!) {\n  definition(id: $definition) {\n    id\n    flavours {\n      id\n      __typename\n    }\n    __typename\n  }\n}"


async def aget_detail_definition(
    definition: ID, rath: Optional[KabinetRath] = None
) -> GetDetailDefinitionQueryDefinition:
    """GetDetailDefinition

    Return all dask clusters

    Args:
        definition (ID): No description
        rath (kabinet.rath.KabinetRath, optional): The client we want to use (defaults to the currently active client)

    Returns:
        GetDetailDefinitionQueryDefinition
    """
    return (
        await aexecute(GetDetailDefinitionQuery, {"definition": definition}, rath=rath)
    ).definition


def get_detail_definition(
    definition: ID, rath: Optional[KabinetRath] = None
) -> GetDetailDefinitionQueryDefinition:
    """GetDetailDefinition

    Return all dask clusters

    Args:
        definition (ID): No description
        rath (kabinet.rath.KabinetRath, optional): The client we want to use (defaults to the currently active client)

    Returns:
        GetDetailDefinitionQueryDefinition
    """
    return execute(
        GetDetailDefinitionQuery, {"definition": definition}, rath=rath
    ).definition
